apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-routes-api
  namespace: sit
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  tls:
  - hosts:
    - api.exops.my.id
    secretName: server-tls
  rules:
  - host: api.exops.my.id
    http:
      paths:
      - path: /ms-posyandu/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: msposyandu
            port:
              number: 80
  ingressClassName: nginx
