apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /sample-php
  name: ingress-routes
  namespace: sit
spec:
  rules:
  - host: sp.paiops.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-php-svc
            port:
              number: 80
  ingressClassName: nginx
