apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mesh-gateway-sample-php-info
  namespace: sit
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-certs
    hosts:
    - mtfa.my.id
