apiVersion: v1
kind: Service
metadata:
  name: msposyandu
  namespace: sit
  labels:
    app: msposyandu
spec:
  selector:
    app: msposyandu
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8099
