apiVersion: apps/v1
kind: Deployment
metadata:
  name: msposyandu
  namespace: sit
  labels:
    app: msposyandu
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: msposyandu
  template:
    metadata:
      labels:
        app: msposyandu
    spec:
      containers:
      - name: msposyandu
        image: taufik90/msposyandu:19
        ports:
        - containerPort: 8099
        livenessProbe:
          httpGet:
            path: /api/v1/healthcek/healty
            port: 8099
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/healthcek/healty
            port: 8099
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 60"]
        env:
         - name: PORT
           value: "8099"
         - name: MYSQL_HOSTNAME
           value: "rm-d9jl3xtniu9x99a4f2o.mysql.ap-southeast-5-rds.paiops.xyz"
         - name: MYSQL_USERNAME
           value: "impsu"
         - name: MYSQL_PASSWORD
           value: "Akbarakbar@99"
         - name: MYSQL_PORT
           value: "3306"
         - name: MYSQL_DATABASE
           value: "ms_psynd"
         - name: ACC_KEY_ID
           value: "006SWZ1KKNP5ED8QLLWS"
         - name: SCR_ACC_KEY
           value: "Qiu9PC6lDbw3byDfX1iJnGdePRtHDrSrww7Lwgkk"
         - name: OSS_REGION
           value: "Jakarta"
         - name: OSS_ENDPOINT
           value: "https://s3-jkt1.dcloud.co.id"
