apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-sit-sample-php-info
  namespace: sit
spec:
  hosts:
  - wev.mtfa.my.id
  gateways:
  - mesh-gateway-sample-php-info
  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: sample-php-info-svc.sit.svc.cluster.local
        port:
          number: 80
